_wandb:
    value:
        cli_version: 0.25.0
        e:
            w4kimd62cpt65ivgjbzi36t24vk4d3s5:
                args:
                    - --dataset
                    - MIMM
                    - --odir
                    - /home/osiris-user/Desktop/TFM/methods/results
                    - --endpoint
                    - OS_6
                    - --model
                    - DyAM
                    - --inst_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//patients_mimm.csv
                    - --patho_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//pathology_mimm.csv
                    - --radio_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radiology_mimm.csv
                    - --clin_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//clinical_mimm.csv
                    - --radio_report_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radioreports_mimm.csv
                    - --blood_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//blood_mimm.csv
                    - --inner_splits
                    - "5"
                    - --outer_splits
                    - "5"
                    - --epochs
                    - "80"
                    - --batch_size
                    - 16,32
                    - --learning_rate
                    - 5e-5,1e-4
                    - --dyam_dropout
                    - 0.2,0.4
                    - --dyam_temperature
                    - 1.0,2.0
                    - --train_missing_prob
                    - 0.0,0.2,0.4,0.6,0.8
                    - --train_missing_location
                    - global, path, radio, clin, blood, radio_report
                    - --test_missing_prob
                    - 0.0,0.2,0.4,0.6,0.8
                    - --test_missing_location
                    - global, path, radio, clin, blood, radio_report
                    - --seeds
                    - 22,2002,4
                    - --wandb
                    - --wandb_project
                    - DyAMs
                    - --wandb_mode
                    - online
                codePath: methods/main.py
                email: albesa.marc@gmail.com
                executable: /home/osiris-user/anaconda3/envs/TFM/bin/python
                git:
                    commit: a61e7fd638963b2d22d67769a9140a3c5e2f847b
                    remote: git@github.com:marcalvi/TFM.git
                host: dd8fc34a3737
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/osiris-user/Desktop/TFM/methods/main.py
                python: CPython 3.9.23
                root: /home/osiris-user/Desktop/TFM/methods/runs
                startedAt: "2026-03-03T11:55:19.772659Z"
                writerId: w4kimd62cpt65ivgjbzi36t24vk4d3s5
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.9.23
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
dataset:
    value: MIMM
endpoint:
    value: OS_6
epochs:
    value: 80
hp_grid_size:
    value: 16
imputation_method:
    value: zero
inner_splits:
    value: 5
modalities:
    value:
        - path
        - radio
        - clin
        - blood
        - radio_report
model:
    value: DyAM
outer_fold:
    value: 1
outer_splits:
    value: 5
phase:
    value: avg_inner_curve_best_per_fold
seed:
    value: 22
selected_inner_hp_names:
    value:
        - lr1e-04_bs16_drop0p4_temp2p0_trmiss60_trlocradio
        - lr5e-05_bs16_drop0p4_temp2p0_trmiss60_trlocradio
        - lr5e-05_bs32_drop0p4_temp2p0_trmiss60_trlocradio
        - lr1e-04_bs16_drop0p2_temp1p0_trmiss60_trlocradio
        - lr1e-04_bs16_drop0p4_temp2p0_trmiss60_trlocradio
test_eval_combinations:
    value: 30
test_missing_locations_grid:
    value: global,path,radio,clin,blood,radio_report
test_missing_probs_grid:
    value: 0.0,0.2,0.4,0.6,0.8
train_missing_location:
    value: radio
train_missing_prob:
    value: 0.6
