_wandb:
    value:
        cli_version: 0.25.0
        e:
            fl7teehcdm4ttecpk0umzrkd0j6my1dq:
                args:
                    - --dataset
                    - MIMM
                    - --odir
                    - /home/osiris-user/Desktop/TFM/methods/results
                    - --endpoint
                    - OS_6
                    - --model
                    - ZI_MLP
                    - --inst_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//patients_mimm.csv
                    - --patho_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//pathology_mimm.csv
                    - --radio_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radiology_mimm.csv
                    - --clin_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//clinical_mimm.csv
                    - --radio_report_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radioreports_mimm.csv
                    - --blood_data
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//blood_mimm.csv
                    - --inner_splits
                    - "5"
                    - --outer_splits
                    - "5"
                    - --epochs
                    - "80"
                    - --batch_size
                    - 16,32
                    - --learning_rate
                    - 5e-5,1e-4
                    - --fusion_hidden_dim
                    - 32,64
                    - --fusion_hidden_layers
                    - "1"
                    - --modality_hidden_layers
                    - "1"
                    - --dropout
                    - 0.2,0.1
                    - --missing_prob
                    - 0.2,0.4,0.6,0.8
                    - --missing_scope
                    - train,test,both,none
                    - --missing_location
                    - global, path, radio, clin, blood, radio_report
                    - --seeds
                    - 22,2002,639
                    - --wandb
                    - --wandb_project
                    - ZI_MLPs
                    - --wandb_mode
                    - online
                codePath: methods/MLPs/main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2013991550976"
                        used: "171910807552"
                email: albesa.marc@gmail.com
                executable: /home/osiris-user/anaconda3/envs/TFM/bin/python
                git:
                    commit: 50293ab1dbacedeaa289cb368de62a94f70d351a
                    remote: git@github.com:marcalvi/TFM.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-50703dc3-eb1a-c0ed-b833-c6ece22c9d00
                host: dd8fc34a3737
                memory:
                    total: "134225829888"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/osiris-user/Desktop/TFM/methods/MLPs/main.py
                python: CPython 3.9.23
                root: /home/osiris-user/Desktop/TFM/methods/MLPs/runs
                startedAt: "2026-03-02T14:19:19.977018Z"
                writerId: fl7teehcdm4ttecpk0umzrkd0j6my1dq
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.23
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
dataset:
    value: MIMM
endpoint:
    value: OS_6
epochs:
    value: 80
hp_grid_size:
    value: 16
inner_splits:
    value: 5
missing_location:
    value: radio_report
missing_prob:
    value: 0.2
missing_scope:
    value: train
modalities:
    value:
        - path
        - radio
        - clin
        - blood
        - radio_report
model:
    value: ZI_MLP
outer_fold:
    value: 2
outer_splits:
    value: 5
phase:
    value: avg_inner_curve_best_per_fold
seed:
    value: 22
selected_inner_hp_names:
    value:
        - lr5e-05_bs16_modL1_fusion32_fusionL1_drop0p2_miss20_scopetrain_locradio_report
        - lr1e-04_bs16_modL1_fusion32_fusionL1_drop0p2_miss20_scopetrain_locradio_report
        - lr1e-04_bs16_modL1_fusion32_fusionL1_drop0p1_miss20_scopetrain_locradio_report
        - lr1e-04_bs32_modL1_fusion64_fusionL1_drop0p1_miss20_scopetrain_locradio_report
        - lr1e-04_bs32_modL1_fusion64_fusionL1_drop0p1_miss20_scopetrain_locradio_report
