_wandb:
    value:
        cli_version: 0.25.0
        e:
            l2zllzs1oawu37x0cgyy3a1zhlbhajcq:
                args:
                    - --model
                    - MLP
                    - --dataset
                    - MIMM
                    - --odir
                    - /nfs/rnas/workspaces/malbesa/TFM/methods//results
                    - --dataset_dir
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM/
                    - --endpoint
                    - OS_6
                    - --inner_splits
                    - "5"
                    - --outer_splits
                    - "5"
                    - --epochs
                    - "80"
                    - --batch_size
                    - 16,32
                    - --learning_rate
                    - 5e-5,1e-4
                    - --fusion_hidden_dim
                    - 32,64
                    - --fusion_hidden_layers
                    - "1"
                    - --modality_hidden_layers
                    - "1"
                    - --dropout
                    - 0.2,0.1
                    - --imputation_method
                    - vae
                    - --vae_imputer_latent_dim
                    - "16"
                    - --vae_imputer_hidden_dim
                    - "128"
                    - --vae_imputer_epochs
                    - "30"
                    - --vae_imputer_batch_size
                    - "64"
                    - --vae_imputer_lr
                    - "1e-3"
                    - --vae_imputer_beta
                    - "1e-3"
                    - --train_missing_prop
                    - 0.0,0.2,0.4,0.6,0.8
                    - --missing_location
                    - global, path, radio, clin, blood, radio_report
                    - --test_missing_prop
                    - 0.0,0.2,0.4,0.6,0.8
                    - --seeds
                    - 22,2002,4,18473,55602
                    - --missing_pattern_seed
                    - "2026"
                    - --wandb
                    - --wandb_project
                    - VAE_MLP
                    - --wandb_mode
                    - online
                email: albesa.marc@gmail.com
                executable: /home/osiris-user/anaconda3/envs/TFM/bin/python
                host: f309fb1b02e5
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /nfs/rnas/workspaces/malbesa/TFM/methods//main.py
                python: CPython 3.9.23
                root: /nfs/rnas/workspaces/malbesa/TFM/methods/runs
                startedAt: "2026-03-19T16:58:55.872848Z"
                writerId: l2zllzs1oawu37x0cgyy3a1zhlbhajcq
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.9.23
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
dataset:
    value: MIMM
endpoint:
    value: OS_6
epochs:
    value: 80
eval_missing_locations_grid:
    value: global,global,global,global,global
hp_grid_size:
    value: 16
imputation_method:
    value: vae
inner_splits:
    value: 5
missing_location:
    value: global
missing_pattern_seed:
    value: 2026
modalities:
    value:
        - path
        - radio
        - clin
        - blood
        - radio_report
model:
    value: mlp
outer_fold:
    value: 1
outer_splits:
    value: 5
phase:
    value: avg_inner_curve_best_per_fold
seed:
    value: 22
selected_inner_hp_names:
    value:
        - lr5e-05_bs16_modL1_fusion64_fusionL1_drop0p2_trmiss40_trlocglobal
        - lr5e-05_bs32_modL1_fusion64_fusionL1_drop0p2_trmiss40_trlocglobal
        - lr5e-05_bs16_modL1_fusion32_fusionL1_drop0p1_trmiss40_trlocglobal
        - lr5e-05_bs16_modL1_fusion32_fusionL1_drop0p1_trmiss40_trlocglobal
        - lr5e-05_bs16_modL1_fusion64_fusionL1_drop0p2_trmiss40_trlocglobal
test_eval_combinations:
    value: 5
test_missing_props_grid:
    value: 0.0,0.2,0.4,0.6,0.8
train_missing_prop:
    value: 0.4
vae_imputer_batch_size:
    value: 64
vae_imputer_beta:
    value: 0.001
vae_imputer_epochs:
    value: 30
vae_imputer_hidden_dim:
    value: 128
vae_imputer_latent_dim:
    value: 16
vae_imputer_lr:
    value: 0.001
