_wandb:
    value:
        cli_version: 0.25.0
        e:
            bwxa4hvhhqdaul80dsm112wouq2oas7g:
                args:
                    - --model
                    - MLP
                    - --dataset
                    - MIMM
                    - --odir
                    - /home/osiris-user/Desktop/TFM/methods/results/results_OS_9_reducedfalse_retraintrue_k4
                    - --dataset_dir
                    - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM/
                    - --endpoint
                    - OS_9
                    - --inner_splits
                    - "4"
                    - --outer_splits
                    - "4"
                    - --epochs
                    - "80"
                    - --retrain_outer
                    - "true"
                    - --reduced_df
                    - "false"
                    - --radio_aggregation_method
                    - mean
                    - --batch_size
                    - 16,32
                    - --learning_rate
                    - 1e-5,5e-5,1e-4
                    - --fusion_hidden_dim
                    - 32,64
                    - --fusion_hidden_layers
                    - "1"
                    - --fusion_batchnorm
                    - "false"
                    - --modality_hidden_layers
                    - "1"
                    - --dropout
                    - 0.2,0.1
                    - --imputation_method
                    - zero
                    - --train_missing_prop
                    - "0.0"
                    - --missing_location
                    - global
                    - --test_missing_prop
                    - "0.0"
                    - --seeds
                    - 22,2002,4,18473,55602
                    - --missing_pattern_seed
                    - "2026"
                    - --wandb
                    - --wandb_project
                    - ZI_MLP_reduced
                    - --wandb_mode
                    - online
                executable: /home/osiris-user/anaconda3/envs/TFM/bin/python
                host: 2ccb820606da
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /home/osiris-user/Desktop/TFM/methods/main.py
                python: CPython 3.9.23
                root: /nfs/rnas/workspaces/malbesa/TFM/methods/runs
                startedAt: "2026-04-14T10:28:09.273236Z"
                writerId: bwxa4hvhhqdaul80dsm112wouq2oas7g
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.9.23
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
best_epoch_warmup:
    value: 5
dataset:
    value: MIMM
endpoint:
    value: OS_9
epochs:
    value: 80
eval_missing_locations_grid:
    value: global
hp_grid_size:
    value: 24
imputation_method:
    value: zero
inner_splits:
    value: 4
missing_location:
    value: global
missing_pattern_seed:
    value: 2026
modalities:
    value:
        - path
        - radio
        - clin
        - blood
        - radio_report
model:
    value: mlp
outer_fold:
    value: 3
outer_refit_epochs:
    value: 6
outer_splits:
    value: 4
phase:
    value: outer_train_refit
radio_aggregation_method:
    value: mean
reduced_df:
    value: false
retrain_outer:
    value: true
seed:
    value: 18473
selected_hp_name:
    value: lr1e-04_bs16_modL1_fusion32_fusionL1_fusionBN0_drop0p1_trmiss0_trlocglobal
test_eval_combinations:
    value: 1
test_missing_props_grid:
    value: "0.0"
train_missing_prop:
    value: 0
