MODEL_CONFIG = {
    "display_name": "HealNet",
    "model": "HealNet",
    "args": {
        "epochs": 100,
        "early_stopping_patience": 20,
        "batch_size": "8,16",
        "learning_rate": "1e-4,5e-5,1e-5",
        "weight_decay": "1e-4",
        "healnet_depth": "1,2",
        "healnet_num_freq_bands": "2",
        "healnet_num_latents": "8,16",
        "healnet_latent_dim": "8,16",
        "healnet_cross_heads": "1",
        "healnet_latent_heads": "2",
        "healnet_cross_dim_head": "8",
        "healnet_latent_dim_head": "8",
        "healnet_attn_dropout": "0.2",
        "healnet_ff_dropout": "0.2",
        "healnet_self_per_cross_attn": "0",
    },
    "paired_args": [
        ("healnet_num_latents", "healnet_latent_dim"),
    ],
}
