wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.23
    cli_version: 0.25.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1772425381
    t:
      1:
      - 1
      - 5
      - 53
      2:
      - 1
      - 5
      - 53
      3:
      - 2
      - 4
      - 13
      - 16
      - 37
      - 42
      - 61
      - 62
      4: 3.9.23
      5: 0.25.0
      13: linux-x86_64
    e:
      7xn4dlee4q4u4l2zc261v0xggjl6zrrm:
        os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
        python: CPython 3.9.23
        started_at: '2026-03-02T04:23:01.249687Z'
        args:
        - --dataset
        - MIMM
        - --odir
        - /home/osiris-user/Desktop/TFM/methods/results
        - --endpoint
        - OS_6
        - --model
        - ZI_MLP
        - --inst_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//patients_mimm.csv
        - --patho_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//pathology_mimm.csv
        - --radio_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radiology_mimm.csv
        - --clin_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//clinical_mimm.csv
        - --radio_report_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//radioreports_mimm.csv
        - --blood_data
        - /nfs/rnas/projects/M3BENCH/data/inputs/MIMM//blood_mimm.csv
        - --inner_splits
        - '5'
        - --outer_splits
        - '5'
        - --epochs
        - '80'
        - --batch_size
        - 16,32
        - --learning_rate
        - 5e-5,1e-4
        - --fusion_hidden_dim
        - 32,64
        - --fusion_hidden_layers
        - '1'
        - --modality_hidden_layers
        - '1'
        - --dropout
        - 0.2,0.1
        - --missing_prob
        - 0.2,0.4,0.6,0.8
        - --missing_scope
        - train,test,both,none
        - --missing_location
        - global, path, radio, clin, blood, radio_report
        - --seeds
        - 4,18473,55602
        - --wandb
        - --wandb_project
        - ZI_MLPs
        - --wandb_mode
        - offline
        program: /home/osiris-user/Desktop/TFM/methods/MLPs/main.py
        code_path: methods/MLPs/main.py
        git:
          remote_url: git@github.com:marcalvi/TFM.git
          commit: b57a7e6918842aa25cefbaa6af70f3d290d2c6eb
        root: /home/osiris-user/Desktop/TFM/methods/MLPs/runs
        host: 348289e06d3a
        executable: /home/osiris-user/anaconda3/envs/TFM/bin/python
        cpu_count: 16
        cpu_count_logical: 32
        gpu_type: NVIDIA GeForce RTX 4090
        gpu_count: 1
        disk:
          /:
            total: '2013991550976'
            used: '171231244288'
        memory:
          total: '134224306176'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 4090
          memory_total: '25757220864'
          cuda_cores: 16384
          architecture: Ada
          uuid: GPU-71165136-92e4-7327-1cd1-4874faaed978
        cuda_version: '13.0'
        writer_id: 7xn4dlee4q4u4l2zc261v0xggjl6zrrm
endpoint:
  desc: null
  value: OS_6
model:
  desc: null
  value: ZI_MLP
dataset:
  desc: null
  value: MIMM
modalities:
  desc: null
  value:
  - path
  - radio
  - clin
  - blood
  - radio_report
hp_grid_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 80
inner_splits:
  desc: null
  value: 5
outer_splits:
  desc: null
  value: 5
missing_prob:
  desc: null
  value: 0.2
missing_scope:
  desc: null
  value: train
missing_location:
  desc: null
  value: path
imputation_method:
  desc: null
  value: zero
seed:
  desc: null
  value: 4
outer_fold:
  desc: null
  value: 2
phase:
  desc: null
  value: avg_inner_curve_best_per_fold
selected_inner_hp_names:
  desc: null
  value:
  - lr1e-04_bs16_modL1_fusion32_fusionL1_drop0p2_miss20_scopetrain_locpath
  - lr1e-04_bs32_modL1_fusion64_fusionL1_drop0p2_miss20_scopetrain_locpath
  - lr5e-05_bs16_modL1_fusion64_fusionL1_drop0p2_miss20_scopetrain_locpath
  - lr5e-05_bs16_modL1_fusion64_fusionL1_drop0p1_miss20_scopetrain_locpath
  - lr5e-05_bs32_modL1_fusion64_fusionL1_drop0p1_miss20_scopetrain_locpath
