_wandb:
    value:
        cli_version: 0.25.0
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.9.23
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
dataset:
    value: MIMM
endpoint:
    value: OS_6
epochs:
    value: 80
hp_grid_size:
    value: 16
imputation_method:
    value: knn
inner_splits:
    value: 5
missing_location:
    value: global
missing_prob:
    value: 0.4
missing_scope:
    value: train
modalities:
    value:
        - path
        - radio
        - clin
        - blood
        - radio_report
model:
    value: KNN_MLP
outer_fold:
    value: 1
outer_splits:
    value: 5
phase:
    value: avg_inner_curve_best_per_fold
seed:
    value: 22
selected_inner_hp_names:
    value:
        - lr5e-05_bs32_modL1_fusion64_fusionL1_drop0p2_miss40_scopetrain_locglobal
        - lr5e-05_bs32_modL1_fusion32_fusionL1_drop0p1_miss40_scopetrain_locglobal
        - lr5e-05_bs16_modL1_fusion64_fusionL1_drop0p2_miss40_scopetrain_locglobal
        - lr1e-04_bs16_modL1_fusion32_fusionL1_drop0p1_miss40_scopetrain_locglobal
        - lr1e-04_bs32_modL1_fusion32_fusionL1_drop0p1_miss40_scopetrain_locglobal
